name: TeleportationCommands
version: '${project.version}'
main: okey_boomer.teleportationcommands.TeleportationCommands
api-version: 1.20.6
commands:
  spawn:
    description: Teleports the player to the world spawn
    usage: /spawn
    aliases: [s]
  tpa:
    description: Teleports the player to another user
    usage: /tpa otherUser
  tpaccept:
    description: Accepts another player's teleport request
    usage: /tpaccept otherUser
  tpdecline:
    description: Declines another player's teleport request
    usage: /tpdecline otherUser
  setWarp:
    description: Sets a new warp location
    usage: /setwarp warpName
    permission: warpOp
  warp:
    description: Teleports the player to a specified location
    usage: /warp warpName
  warps:
    description: Lists all warp locations
    usage: /warps
  deleteWarp:
    description: Removes warp with the given name
    usage: /deleteWarp warpName
    permission: warpOp
  setHome:
    description: Sets the player's home to their current location
    usage: /setHome homeName
  home:
    description: Teleports the player to their home
    usage: /home homeName
  homes:
    description: Lists a player's homes
    usage: /homes
  deleteHome:
    description: Removes the player's home
    usage: /deleteHome homeName
  back:
    description: Returns the player to last death location
    usage: /back